<!-- @generated by @medienakzent/cms 0.8.10 — do not edit, replaced on updates (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/Users.svelte';

	let { data } = $props();
</script>

<Page {data} />
