<!-- @generated by @medienakzent/cms 0.5.3 — do not edit, replaced on updates (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/New.svelte';

	let { data, form } = $props();
</script>

<Page {data} {form} />
