<!-- @generated by @medienakzent/cms 0.4.0 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/Document.svelte';

	let { data } = $props();
</script>

{#key `${data.collection.name}/${data.doc.slug}/${data.lang}/${data.doc.updatedAt}`}
	<Page {data} />
{/key}
