<!-- @generated by @medienakzent/cms 0.1.2 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync) -->
<script lang="ts">
	import '../../admin.css';
	import Layout from '@medienakzent/cms/pages/admin/Layout.svelte';
	import registry from '../../cms';

	let { data, children } = $props();
</script>

<Layout {data} {registry} {children} />
