<!-- @generated by @medienakzent/cms 0.4.0 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/Dashboard.svelte';

	let { data } = $props();
</script>

<Page {data} />
