<!-- @generated by @medienakzent/cms 0.8.8 — do not edit, replaced on updates (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/ApiKeyNew.svelte';
</script>

<Page />
