<!-- @generated by @medienakzent/cms 0.9.0 — do not edit, replaced on updates (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/Media.svelte';

	let { data } = $props();
</script>

<Page {data} />
