// @generated by @medienakzent/cms 0.6.2 — do not edit, replaced on updates (npx cms sync)
import { createLangMatcher } from '@medienakzent/cms/routes/params';
import registry from '../cms';

export const match = createLangMatcher(registry);
