// @generated by @compdata/cms 0.1.0 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync)
import { createLangMatcher } from '@compdata/cms/routes/params';
import registry from '../cms';

export const match = createLangMatcher(registry);
