<!-- @generated by @medienakzent/cms 0.1.2 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/Submissions.svelte';

	let { data } = $props();
</script>

<Page {data} />
