<!-- @generated by @medienakzent/cms 0.3.0 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync) -->
<script lang="ts">
	import '../../../admin.css';
	import Page from '@medienakzent/cms/pages/admin/Login.svelte';

	let { data } = $props();
</script>

<Page {data} />
