<!-- @generated by @medienakzent/cms 0.8.13 — do not edit, replaced on updates (npx cms sync) -->
<script lang="ts">
	import '../../../admin.css';
	import Page from '@medienakzent/cms/pages/admin/Login.svelte';

	let { data } = $props();
</script>

<Page {data} />
