<!-- @generated by @medienakzent/cms 0.6.0 — do not edit, replaced on updates (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/UserNew.svelte';
</script>

<Page />
