// @generated by @medienakzent/cms 0.3.0 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync)
export { GET_ITEM as GET, DELETE_ITEM as DELETE } from '@medienakzent/cms/routes/api/submissions';
