<!-- @generated by @compdata/cms 0.1.0 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync) -->
<script lang="ts">
	import Page from '@compdata/cms/pages/admin/Mail.svelte';

	let { data } = $props();
</script>

<Page {data} />
