// @generated by @medienakzent/cms 0.2.1 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync)
import { building } from '$app/environment';
import { env } from '$env/dynamic/private';
import { createHandle } from '@medienakzent/cms/server';
import registry from './cms';

export const handle = createHandle(registry, { env, building });
