// @generated by @medienakzent/cms 0.8.3 — do not edit, replaced on updates (npx cms sync)
import { building } from '$app/environment';
import { env } from '$env/dynamic/private';
import { createHandle } from '@medienakzent/cms/server';
import registry from './cms';

export const handle = createHandle(registry, { env, building });
