<!-- @generated by @medienakzent/cms 0.8.6 — do not edit, replaced on updates (npx cms sync) -->
<script lang="ts">
	import Page from '@medienakzent/cms/pages/admin/SubmissionDetail.svelte';

	let { data } = $props();
</script>

<Page {data} />
