// @generated by @medienakzent/cms 0.2.1 — nicht bearbeiten, wird bei Updates ersetzt (npx cms sync)
export { GET_ITEM as GET, PATCH_ITEM as PATCH, DELETE_ITEM as DELETE } from '@medienakzent/cms/routes/api/media';
