// @generated by @medienakzent/cms 0.8.15 — do not edit, replaced on updates (npx cms sync)
export {
	GET_ITEM as GET,
	PATCH_ITEM as PATCH,
	DELETE_ITEM as DELETE
} from '@medienakzent/cms/routes/api/media';
